services:
  db:
    image: postgres:16
    container_name: voicebridge_db
    restart: always
    environment:
      POSTGRES_DB: voicebridge
      POSTGRES_USER: voicebridge_user
      POSTGRES_PASSWORD: voicebridge_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: