# Generated by Django 6.1 on 2026-08-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryentry',
            options={'verbose_name_plural': 'Memory Entries'},
        ),
    ]
